INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (53,'Alabama',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (54,'Alaska',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (55,'Arizona',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (56,'Arkansas',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (57,'California',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (58,'Colorado',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (59,'Connecticut',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (60,'Delaware',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (61,'Florida',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (62,'Georgia',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (63,'Hawaii',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (64,'Idaho',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (65,'Illinois',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (66,'Indiana',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (67,'Iowa',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (68,'Kansas',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (69,'Kentucky',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (70,'Louisiana',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (71,'Maine',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (72,'Maryland',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (73,'Massachusetts',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (74,'Michigan',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (75,'Minnesota',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (76,'Mississippi',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (77,'Missouri',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (78,'Montana',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (79,'Nebraska',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (80,'Nevada',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (81,'New Hampshire',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (82,'New Jersey',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (83,'New Mexico',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (84,'New York',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (85,'North Carolina',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (86,'North Dakota',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (87,'Ohio',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (88,'Oklahoma',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (89,'Oregon',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (90,'Pennsylvania',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (91,'Rhode Island',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (92,'South Carolina',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (93,'South Dakota',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (94,'Tennessee',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (95,'Texas',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (96,'Utah',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (97,'Vermont',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (98,'Virginia',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (99,'Washington',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (100,'West Virginia',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (101,'Wisconsin',3,null);
INSERT INTO app_states (id,title,country_id,ccaa_id) VALUES (102,'Wyoming',3,null);
