INSERT INTO app_ccaa (id,title,country_id) VALUES (1,'Andalucía',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (2,'Aragón',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (3,'Asturias',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (4,'Baleares',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (5,'Canarias',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (6,'Cantabria',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (7,'Castilla y León',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (8,'Castilla - La Mancha',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (9,'Cataluña',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (10,'Comunidad Valenciana',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (11,'Extremadura',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (12,'Galicia',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (13,'Comunidad de Madrid',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (14,'Región de Murcia',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (15,'Navarra',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (16,'País Vasco',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (17,'La Rioja',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (18,'Ceuta',1);
INSERT INTO app_ccaa (id,title,country_id) VALUES (19,'Melilla',1);